[package]
name = "logfmt"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared tracing event formatting for hotki"

[dependencies]
tracing = { workspace = true }

